### ISSUE TITLE
Perception Problems

### ISSUE THREAD

**Issue by chibi314** [tongtybj/jsk_uav_forest#8]
現在, Tree Detectionには幾つか問題がある．

1. 機体が傾いた時にURGの測定平面が傾く→地面に当たる→今のアルゴリズムだと木と誤認識しうる
 1.1 速度→姿勢(roll, pitch)へのゲインを下げて傾きを小さくする
 1.2 自分の高度+姿勢の情報があれば，地面を測定しているrangesは分かるはず→フィルタリングできる
    いや，地面が平面ならいいけど傾いてたら無理だ（競技場も傾斜あるし）
 1.3 アルゴリズムの改良→地面は木としてはあまりにもでかすぎる（はず）→カットできる
 1.4 機体姿勢を考慮して、水平な平面に点を投影する(追記)

2. 赤色を使った目標木認識が不安
 2.1 カメラが不安→カメラ選定，パラメータ調整
 2.2 7m離れてるとちゃんと検出できるか不安　森の中だと暗そう
 2.3 'rosservice call /sub_control true'したときに赤色検出ができてなかった場合はどうなる？→探索動作が必要？ xyに動く or yawを回す→ tree detection start → あったらやる or なかったら探索続行

3. そもそも赤色検出が不安→相対的な関係を使う？

**Comment by tongtybj** [comment]
@chibi314 
>  1.1 速度→姿勢(roll, pitch)へのゲインを下げて傾きを小さくする
[ここ](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/blob/indigo-devel/hector_quadrotor_controller/params/controller.yaml#L33g)をちいさくすれば、急な傾きは消える。
問題はhector_quadrotor_controller内のファイルだから、ホントはいじっては行けないと思うけど、第１回一週間プロジェクトなら許される。

**Comment by tongtybj** [comment]
@chibi314 
@chibi314 
> 1.2 自分の高度+姿勢の情報があれば，地面を測定しているrangesは分かるはず→フィルタリングできる

いや，地面が平面ならいいけど傾いてたら無理だ（競技場も傾斜あるし）
傾斜は僕も思った、あと上に向くと今度は枝とかに当たる気がする。
第1回一週間プロジェクトでは、絶対しきい値でフィルタしてみると思います。
あと、現状でも地面にあたっても誤認識しないはず。これも原因を探ってみる。

**Comment by tongtybj** [comment]
@chibi314 

>  1.3 アルゴリズムの改良→地面は木としてはあまりにもでかすぎる（はず）→カットできる

tree clustering(元のfootobject scan)ではmax_radius以上のものは除去するようになっている。今は0.4にしているけど、地面カットできていないかな。

**Comment by chibi314** [comment]
@tongtybj 
たしかに枝があるし、結構根深い問題ですね・・・
簡単なのはあまりに傾きが大きい時のデータは使わない、とかでしょうか
clusteringは上限あるんでしたね　だとすると、ごくたまに地面をスキャンして、得られたクラスタのサイズがちょうどよいかつ元の木の位置と近い時にそこをずっと木だと認識してしまう（水平になったときにそこに明らかに木はないけれど、何かの理由で見えていないだけで本当はあると扱う）問題があると思います

**Comment by tongtybj** [comment]
@chibi314 

>   簡単なのはあまりに傾きが大きい時のデータは使わない、とかでしょうか

今週はこれで行こう(来週からは第2回一週間プロジェクト)！

>  得られたクラスタのサイズがちょうどよいかつ元の木の位置と近い時にそこをずっと木だと認識してしまう

激しく同意

**Comment by tongtybj** [comment]
@chibi314 

> 2.3 'rosservice call /sub_control true'したときに赤色検出ができてなかった場合はどうなる？→探索動作が必要？ xyに動く or yawを回す→ tree detection start → あったらやる or なかったら探索続行

第1回一週間プロジェクトなら、　確実に見える範囲まで前進してから、 rosserial call でいいと思う。
第2回一週間プロジェクトなら、　探索動作を入れて、[ここ](https://github.com/tongtybj/jsk_uav_forest/blob/perception/jsk_uav_forest_perception/src/tree_detector.cpp#L195-L201)に色検出と木との最大角度差の閾値をいれて、これを目標木の検出判定にしておけばいいと思っている。

**Comment by tongtybj** [comment]
@chibi314 

> 2.1 カメラが不安→カメラ選定，パラメータ調整

明日の柏実験が終わったら、ウェブカメラもらいに行こう。

> 2.2 7m離れてるとちゃんと検出できるか不安　森の中だと暗そう
> そもそも赤色検出が不安→相対的な関係を使う？

第2回一週間プロジェクトの案としては、昨日ラインで話した。
tree clustering -> tree region内でのHueのヒストグラム分析 -> 目標パターンに一番近いものを選ぶ
というのはどうかな。

**Comment by tongtybj** [comment]
#12 にも関連の課題について議論しています

**Comment by tongtybj** [comment]
First detectionで、他の木でも赤に近い検出がされ、それでご認識することがある。
解決案としては、color_region_diretctionとtree clusteringのdiffの投票制か、tree clusteringのwindowを抽出してパターンの相関を比較するという2通りの方法があると思う。
前者はtree clusteringの記録をしないと行けないけど、そんなにめんどくさくないはず。

**Comment by tongtybj** [comment]
顧問・溝花と議論した結果、以下の結論に至りました。
ロバストな認識(特に画像処理を含む初期検出)を実現するには,
1) カメラの選定を行う #13 
2) ロバストtemplate matchingを行う
tree clusteringによるROIの抽出 -> ROI内のhue値の抽出(Lev2は溝花案のhue, saturationの主成分分析) -> 赤・緑・青を用いたオフセット付きのtemplate matching
3) tree clusteringでlaserscanによる2Dclusteringかstereoによる3D clustering, これも評価するべきである。

**Comment by chibi314** [comment]
tree_detection.cppのclurstering_min_points_について
すべてのクラスタはこの数以上の要素数にはならないようになっているが、物体との距離によってサンプリングされる点は変化するので微妙に思える。
仮に大きいクラスタになった場合はclurstering_max_radius_ でカットされる？

**Comment by tongtybj** [comment]
@chibi314 @KahnShi 
with #32 , the framework about the perception is totally changed.
First of all, I have to emphasize that we only use image data for the first target tree detection, acting as a trigger for the target tree tracking. Subsequently, the target tree is only tracked by laser scan data, which shows high reliability in the [real experiment](https://drive.google.com/open?id=0B5zEvOJl5IsDZVFnak8tdWY0Q0E).

In the past, I implemented so-called independent(独立) HSV filter which filtering with the entire image using red hue threshold, then consider the closed tree to the color region center. However, the potential  problem of method is that if there is a large red region in the background like following situation, the the wrong tree with larger red mark is selected as the target(blue point is the color region center).
![independent_hsv_filter_comera_compensation](https://cloud.githubusercontent.com/assets/3666095/25315797/0f9c06f6-2896-11e7-84c0-ae0e1e6798ea.png)
#  **But, in the real competition environment, there is no large red region besides the red marker. Means, the current method is enough for the competition.**
![real_enviroment](https://cloud.githubusercontent.com/assets/3666095/25315828/900536fa-2896-11e7-9e2f-ced0f1e6519d.png)

# TL;DR

But just in case, we have to prepare a more robust detection method, what I call conditional(条件付き) vision filter.
That is we first do the tree clustering and then only do the image process inside each ROI of the tree area. The following example is the conditional  HSV filter, which regard the tree with the largest red region as the target one. The blue rectangle indicates the interest area for the image process. 
![conditional_hsv_filter_camera_compensation](https://cloud.githubusercontent.com/assets/3666095/25315879/90bffa20-2897-11e7-9e3c-f6a0292c5ce5.png)

If we want more robust method, we can apply template matching in side each ROI using hue information. The template may look like the following image.
![template00](https://cloud.githubusercontent.com/assets/3666095/25315898/eed0624e-2897-11e7-8d02-5033bfdaffa7.png)

The remaining problem with the conditional vision filter is the physical offset between the laser sensor center and camera center, which make a huge influence on the ROI extraction in the input image as shown in the following image. You can see the center of ROI does no match the center of the tree, and again wrong tree is selected because there is the red wall in the wrong ROI. 
![conditional_hsv_filter_no_camera_compensaton](https://cloud.githubusercontent.com/assets/3666095/25315946/cfb3a988-2898-11e7-8243-aaaee349508c.png).

# To conclude, we need to design a good mount for the camera but not the temporary tape.

**Comment by tongtybj** [comment]
change the vision detection method [here](https://github.com/tongtybj/jsk_uav_forest/blob/perception/jsk_uav_forest_perception/launch/image_process.launch#L5)

**Comment by chibi314** [comment]
I think conditional hsv filter is a good solution and enough robust.
